---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka,http://eureka-secondary:8011/eureka,http://eureka-tertiary:8012/eureka

---
spring:
  profiles: lab
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka,http://eureka-secondary:8011/eureka,http://eureka-tertiary:8012/eureka
      
---
spring:
  profiles: pdn
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka,http://eureka-secondary:8011/eureka,http://eureka-tertiary:8012/eureka
