spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/d-amaya/spring-cloud-app.git
          searchPaths: ConfigData

server:
  port: 8001

management:
  security:
    enabled: false